core/urls.py
from django.urls import path
from core.views.category.view import *
from core.views.dashboard.view import *
from core.views.sensor.view import *

app_name = 'core'

urlpatterns = [
    # Category
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/add/', CategoryCreateView.as_view(), name='category_create'),
    path('category/form/', CategoryFormView.as_view(), name='category_form'),
    path('category/edit/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    #Dashboard
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    #Sensores
    path('api/sensor-data', SensorDataView.as_view(), name='sensor-data'),
    path('sensores/list/', SensoresListView.as_view(), name='sensores_list'),
    path('led/', ControllerLedUpdateView.as_view(), name='led_control'),
    path('led/status/', LedStatusView.as_view(), name='led_status'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import IndexView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
    path('login/', include('login.urls')),
    path('', IndexView.as_view(), name='index'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'

templates/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition layout-top-nav">
    <div class="wrapper">
        <!-- Header -->
        {% include 'header.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>Example 3.0</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="#">Layout</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block Js -->
    {% block JavaScript %}

    {% endblock %}
    </body>
{% endblock %}

templates/delete.html
{% extends 'layout.html' %}

{% load widget_tweaks %}

{% block content %}
    <form method="post" action=".">
        <div class="card">
            <link rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
            <div class="card-header">

                <h3 class="card-title">
                    <i class="fa-trash fa-solid fa-magnifying-glass-plus"></i>
                    {{ title }}
                </h3>
                <i class="fa-solid fa-shield-halved"></i>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <div class="modal-content bg-danger">
                    <div class="modal-header">
                        <h4 class="modal-title">Notificacion</h4>
                        ¿Esta seguro de eliminar el registro No.{{ object.id }}?
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fa-solid fa-save"></i> Si, aceptar
                </button>
                <a href="{{ list_url }}" type="submit" class="btn btn-primary btn-flat">
                    <i class="fa-solid fa-save"></i> Cancelar
                </a>
            </div>

        </div>
    </form>
{% endblock %}

templates/footer.html
 <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
  </footer>

templates/form.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block content %}
    <form method="post" action=".">
        <div class="card">
            <link rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
            <div class="card-header">

                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="fa-plus fa-solid fa-magnifying-glass-plus"></i>
                    {% else %}
                        <i class="fa-pen fa-solid fa-magnifying-glass-plus"></i>
                    {% endif %}

                    {{ title }}
                </h3>
                <i class="fa-solid fa-shield-halved"></i>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="Category">
                            {{ field.label }}
                        </label>
                        {{ field|attr:"class:form-control" }}
                    </div>
                {% endfor %}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fa-solid fa-save"></i> Guardar resgistro
                </button>
                <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>

        </div>
    </form>
    <script>
        {% if form.errors %}
            var errors = ''
            {% for field in form %}
                {% for error in field.errors %}
                    errors += '{{ error }}\n'
                {% endfor %}
            {% endfor %}
            Swal.fire({
                icon: "error",
                title: "Error!",
                text: errors
            });
        {% endif %}

        {#$('form').on('submit', function (e) {#}
        {#    Alert_JQueryConfirm();#}
        {#});#}


        /*  $('form').on('submit', function (e) {
              e.preventDefault();
              var parameters = $(this).serializeArray();
              $.ajax({
                  url: '{% url 'core:category_create' %}',
                type: 'POST',
                data: parameters,
                datatype: 'json'
            }).done(function (data) {
                if (!data.hasOwnProperty('error')) {
                    location.href = '{{ list_url }}';
                    return false;
                }

                message_error(data.error);
            }).fail(function (jqXHR, textStatus, errorThrown) {
                alert(textStatus + ':' + errorThrown);
            }).always(function (data) {
            });
        });*/

    </script>

{% endblock %}

templates/header.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
    <div class="container">
        <a href="#" class="navbar-brand">
            <img src="{% static 'img/logo.png' %}" alt="AdminLTE Logo"
                 class="brand-image"
                 style="opacity: .8">
            <span class="brand-text font-weight-light">Hades</span>
        </a>
        <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse order-3" id="navbarCollapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="#" class="nav-link"><i class="fas fa-home"></i> Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link dropdown-toggle"><i class="fas fa-folder-open"></i> Mantenimientos</a>
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="#" class="dropdown-item"><i class="fas fa-truck-loading"></i> Categorías</a></li>
                        <li><a href="#" class="dropdown-item"><i class="fas fa-boxes"></i> Productos</a></li>
                        <li><a href="#" class="dropdown-item"><i class="fas fa-users"></i> Clientes</a></li>
                        <li><a href="#" class="dropdown-item"><i class="fas fa-shopping-cart"></i> Ventas</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-bell"></i>
                    <span class="badge badge-warning navbar-badge">15</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header">15 Notifications</span>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-envelope mr-2"></i> 4 new messages
                        <span class="float-right text-muted text-sm">3 mins</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-users mr-2"></i> 8 friend requests
                        <span class="float-right text-muted text-sm">12 hours</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-file mr-2"></i> 3 new reports
                        <span class="float-right text-muted text-sm">2 days</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{{ title }}</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.2.0/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.2.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.2.0/js/adminlte.min.js' %}"></script>
    <!-- SweetAlert2 -->
    <script src="{% static 'lib/sweetAlert2/dist/sweetalert2.all.min.js' %}"></script>
    <script src="{% static 'lib/sweetAlert2/dist/sweetalert2.min.css' %}"></script>
    <!--JQuery-Confirm -->
    <script src="{% static 'lib/jquery-confirm-v3.3.4/dist/jquery-confirm.min.css' %}"></script>
    <script src="{% static 'lib/jquery-confirm-v3.3.4/dist/jquery-confirm.min.js' %}"></script>
    <!-- Funciones -->
    <script src="{% static 'js/funtions.js' %}"></script>
    <!-- Block head -->
    {% block head %}

    {% endblock %}
</head>
{% block body %}

{% endblock %}
</html>

templates/layout.html
{% extends 'vtc/body.html' %}

templates/list.html
{% extends 'vtc/body.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}">
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>

    {% block head_list %}

    {% endblock %}

{% endblock %}
{% block content %}
    <div class="card">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <div class="card-header">

            <h3 class="card-title">
                <i class="fa-duotone fa-solid fa-magnifying-glass-plus"></i>
                {{ title }}
            </h3>
            <i class="fa-solid fa-shield-halved"></i>
        </div>

        <div class="card-body">
            <table class="table" id="data">
                <thead>
                {% block columns %}

                {% endblock %}

                </thead>
                <tbody>
                {% block rows %}

                {% endblock %}


                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <a href="{{ create_url }}" class="btn btn-primary btn-flat btnTest">
                <i class="fa-solid fa-plus"></i>Nuevo resgistro
            </a>
            <a href="{{ list_url }}" class="btn btn-success btn-flat">
                <i class="fas fa-sync"></i> Actualizar
            </a>
        </div>

    </div>
{% endblock %}
{% block JavaScript %}
    <script> type = "application/javascript" >
        $(document).ready(function () {
            $('#data').DataTable(
                {
                    responsive: true,
                    autoWidth: false
                });
            $('.btnTest').on('click', function () {
                /*  $.ajax({
                      url: '

                {% url 'core:category_list' %}',
                    type: 'POST',
                    data: {id: 1},
                    datatype: 'json'
                }).done(function (data) {
                    console.log(data)
                }).fail(function (jqXHR, textStatus, errorThrown) {


                {#alert(textStatus + '='+ errorThrown);#}
                }).always(function (data) {
                });*/
            });
        });
    </script>
{% endblock %}